---
services:
  postgres:
    image: postgres:15
    container_name: blog_postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
